### ISSUE TITLE
[Event]: R Validition Hub Risk Tools Developer Day

### ISSUE THREAD

**Issue by dgkf** [pharmaR/events#57]
### Event Summary

The various risk package teams will host a 2hr workshop session, primarily used to gather developer feedback and introduce new developers to the various packages.

### Target Date

Nov 1st, 2024; 11am-1pm ET

### Event Preparation Timeline

_By target due date_

#### 28 Days Prior

- [x] [Planning] Title & abstract prepared
- [x] [Marketing] Pass along title and abstract info to R/Pharma organizers
- [ ] [Marketing] Send out publicity info to draw people to [R/Pharma](https://rinpharma.com/)
  - Can we get a banner graphic and ask the R Consortium to put out a linked-in/social media blast to recruit to this workshop?

#### 7 Days Prior

- [ ] [Planning] Event materials prepared
- [ ] [Marketing] Send out reminder email

**Comment by dgkf** [comment]
@jcabercrombie I'd like to put together a graphic for this. Maybe we can a banner from the Story Changes Culture folks. Key details:

- What: R Validation Hub Risk Tools Developer Day (ideally with R Validation Hub logo)
- Where: R/Pharma Virtual
- When: Nov 1st, 11am-1pm ET  (I think this is _mostly_ final, but need to confirm before anything goes out)
- What Else: Join us. Looking for new and experienced R Validation Hub contributors alike to onboard to our ecosystem and help brainstorm what comes next.

**Comment by jcabercrombie** [comment]
Sounds like a plan, @dgkf ! I'll reach out to the Story Changes Culture folks so we can get this going. After we receive the graphic for this, we can do an email out to the mailing list! 

Do we have an idea when we'd finalize the time?

**Comment by dgkf** [comment]
> Do we have an idea when we'd finalize the time?

Just recapping our discussion on another platform. No, but it looks like they're prepping material to go out soon. I don't expect the slot to change. For now we'll put together an announcement without a time and just link out to the R/Pharma website for the exact slot info.

**Comment by dgkf** [comment]
@pharmaR/ws-communications adding a link to the recently posted workshop schedule:
https://rinpharma.com/post/2024-10-13-workshops/

**Comment by dgkf** [comment]
Adding a small abstract to add a bit more context to the workshop.

> The R Validation Hub is excited to host the first Risk Tools Developer Day as a workshop at the upcoming R/Pharma Virtual conference. It will be an opportunity for interested developers and stakeholders to come together to connect, share experiences and plan next steps for the collection of R Validation Hub tools. We'll summarize the past year of development and industry trends that might impact the direction of our tools, providing a forum for feeding back into our development efforts to impact our future direction.
>
> This year marks a particularly productive year for the industry, prompting more intentional developer direction. Our risk tools are being more widely adopted than ever, leading to new products built atop or around R Validation Hub tools and expectations about how they should behave. As these tools begin to take on a new life in downstream applications, we are taking this opportunity to learn from how they're put into practice and re-align our development efforts with new knowledge about how they've been most useful and areas where they can be improved.
>
> This workshop will be an open conversation about how we want to structure our teams, tools and future development to best align with our ambitions. We look forward to welcoming first time participants and long-standing contributors alike who are passionate about the role that shared software can play in the rigorous adoption of R and its package ecosystem.

**Comment by dgkf** [comment]
Closing as success 🎉
