### ISSUE TITLE
[Planning] Title & abstract prepared

### ISSUE THREAD

**Issue by aclark02-arcus** [pharmaR/events#60]
Hi @jthompson-arcus, here is an initial start. Let me know your thoughts and we'll submit it to Joanna @ Appsilon by Friday (tomorrow).

**Speakers**: Aaron Clark & Jeff Thompson

**Title**: Workshop: evaluate package quality with the {riskassessment} application

**Abstract**: 
Have you ever needed an R package that performs a vital task for an analysis you're developing, but it has not been qualified for your organization's validated GxP environment? When you asked to add it, did you ever get any pushback? Were you asked to justify why it should be added? During this workshop, we'll demonstrate how to use the {riskassessment} application from the R Validation Hub serves as a hands-on tool for its users to build a case to qualify the package with org-specific lens. Whether you're new to risk assessment or looking to enhance your existing processes, this workshop will offer practical insights to help you navigate risk with confidence.

**Comment by jthompson-arcus** [comment]
@aclark02-arcus The pacing feels a little off to me at the beginning of the abstract. I rewrote it a little, let me know what you think.

You have been tasked with implementing a new analysis into your organization’s workflow. With some exploration, you found an R package that not only solves your problem for you but also includes nice features you haven’t even thought about yet. There’s just one problem, the package has not been qualified for your organization’s validated GxP environment. Does this sound familiar? When you asked to add it, were you met with any pushback? Or maybe you were asked to justify its inclusion? During this workshop, we will demonstrate how the {riskassessment} application from the R Validation Hub can serve as a hands-on tool for its users to build a case to qualify R packages with an org-specific lens. Whether you're new to risk assessment or looking to enhance your existing processes, this workshop will offer practical insights to help you navigate risk with confidence.

**Comment by aclark02-arcus** [comment]
Cool, looks good. What do you think of the below? I tried to laser some of the wordiness and make it flow better.

Have you ever discovered an R package that not only solves a problem but even includes features you haven’t yet thought through? Has that inner joy ever been cut short when you learn the package was not qualified for your validated GxP environment? When you asked to add it, were you met with pushback? Or perhaps you were asked to justify its inclusion?

During this workshop, we will demonstrate how the R Validation Hub's {riskassessment} application can help build a case to qualify R packages with an org-specific lens. Whether you are new to risk assessment or you govern your GxP environment's package lists, this workshop will offer practical insights to help you navigate risk at your organization with confidence.

**Comment by jthompson-arcus** [comment]
Works for me!

**Comment by aclark02-arcus** [comment]
Email sent to Joanna on 12/20
